#
# Constant definitions for spells scripts
#

EFF_TARGET_NONE                     = 0
EFF_TARGET_SELF                     = 1
EFF_TARGET_PET                      = 5
EFF_TARGET_SINGLE_ENEMY             = 6
EFF_TARGET_ALL_ENEMY_IN_AREA            = 15
EFF_TARGET_ALL_ENEMY_IN_AREA_INSTANT    = 16
EFF_TARGET_ALL_PARTY_AROUND_CASTER      = 20
EFF_TARGET_SINGLE_FRIEND                = 21
EFF_TARGET_ALL_ENEMIES_AROUND_CASTER    = 22
EFF_TARGET_GAMEOBJECT                   = 23
EFF_TARGET_IN_FRONT_OF_CASTER           = 24
EFF_TARGET_GAMEOBJECT_ITEM              = 26
EFF_TARGET_ALL_ENEMY_IN_AREA_CHANNELED  = 28
EFF_TARGET_MINION                       = 32
EFF_TARGET_SINGLE_PARTY                 = 35
EFF_TARGET_CHAIN                        = 45
EFF_TARGET_CURRENT_SELECTION            = 53


#-----------------------------------------------------------------
# Spell Aura numbers, used to register Aura handlers
#-----------------------------------------------------------------
SPELL_AURA_BIND_SIGHT = 1                          # Bind Sight
SPELL_AURA_MOD_THREAT = 10                         # Mod Threat
SPELL_AURA_AURAS_VISIBLE = 100                     # Auras Visible
SPELL_AURA_MOD_RESISTANCE_PCT = 101                # Mod Resistance %
SPELL_AURA_MOD_CREATURE_ATTACK_POWER = 102         # Mod Creature Attack Power
SPELL_AURA_MOD_TOTAL_THREAT = 103                  # Mod Total Threat (Fade)
SPELL_AURA_WATER_WALK = 104                        # Water Walk
SPELL_AURA_FEATHER_FALL = 105                      # Feather Fall
SPELL_AURA_HOVER = 106                             # Hover
SPELL_AURA_ADD_FLAT_MODIFIER = 107                 # Add Flat Modifier
SPELL_AURA_ADD_PCT_MODIFIER = 108                  # Add % Modifier
SPELL_AURA_ADD_TARGET_TRIGGER = 109                # Add Class Target Trigger
SPELL_AURA_MOD_TAUNT = 11                          # Taunt
SPELL_AURA_MOD_POWER_REGEN_PERCENT = 110           # Mod Power Regen %
SPELL_AURA_ADD_CASTER_HIT_TRIGGER = 111            # Add Class Caster Hit Trigger
SPELL_AURA_OVERRIDE_CLASS_SCRIPTS = 112            # Override Class Scripts
SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN = 113           # Mod Ranged Dmg Taken
SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT = 114       # Mod Ranged % Dmg Taken
SPELL_AURA_MOD_HEALING = 115                       # Mod Healing
SPELL_AURA_IGNORE_REGEN_INTERRUPT = 116            # Regen During Combat
SPELL_AURA_MOD_MECHANIC_RESISTANCE = 117           # Mod Mechanic Resistance
SPELL_AURA_MOD_HEALING_PCT = 118                   # Mod Healing %
SPELL_AURA_SHARE_PET_TRACKING = 119                # Share Pet Tracking
SPELL_AURA_MOD_STUN = 12                           # Stun
SPELL_AURA_UNTRACKABLE = 120                       # Untrackable
SPELL_AURA_EMPATHY = 121                           # Empathy (Lore whatever)
SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT = 122            # Mod Offhand Dmg %
SPELL_AURA_MOD_POWER_COST_PCT = 123                # Mod Power Cost %
SPELL_AURA_MOD_RANGED_ATTACK_POWER = 124           # Mod Ranged Attack Power
SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN = 125            # Mod Melee Dmg Taken
SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT = 126        # Mod Melee % Dmg Taken
SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS = 127# Rngd Atk Pwr Attckr Bonus
SPELL_AURA_MOD_POSSESS_PET = 128                   # Mod Possess Pet
SPELL_AURA_MOD_INCREASE_SPEED_ALWAYS = 129         # Mod Speed Always
SPELL_AURA_MOD_DAMAGE_DONE = 13                    # Mod Damage Done
SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS = 130          # Mod Mounted Speed Always
SPELL_AURA_MOD_CREATURE_RANGED_ATTACK_POWER = 131  # Mod Creature Ranged Attack Power
SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT = 132       # Mod Increase Energy %
SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT = 133       # Mod Max Health %
SPELL_AURA_MOD_MANA_REGEN_INTERRUPT = 134          # Mod Interrupted Mana Regen
SPELL_AURA_MOD_HEALING_DONE = 135                  # Mod Healing Done
SPELL_AURA_MOD_HEALING_DONE_PERCENT = 136          # Mod Healing Done %
SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE = 137         # Mod Total Stat %
SPELL_AURA_MOD_HASTE = 138                         # Haste - Melee
SPELL_AURA_FORCE_REACTION = 139                    # Force Reaction
SPELL_AURA_MOD_DAMAGE_TAKEN = 14                   # Mod Damage Taken
SPELL_AURA_MOD_RANGED_HASTE = 140                  # Haste - Ranged
SPELL_AURA_MOD_RANGED_AMMO_HASTE = 141             # Haste - Ranged (Ammo Only)
SPELL_AURA_MOD_BASE_RESISTANCE_PCT = 142           # Mod Base Resistance %
SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE = 143          # Mod Resistance Exclusive
SPELL_AURA_SAFE_FALL = 144                         # Safe Fall
SPELL_AURA_CHARISMA = 145                          # Charisma
SPELL_AURA_PERSUADED = 146                         # Persuaded
SPELL_AURA_ADD_CREATURE_IMMUNITY = 147             # Add Creature Immunity
SPELL_AURA_RETAIN_COMBO_POINTS = 148               # Retain Combo Points
SPELL_AURA_DAMAGE_SHIELD = 15                      # Damage Shield
SPELL_AURA_MOD_STEALTH = 16                        # Mod Stealth
SPELL_AURA_MOD_DETECT = 17                         # Mod Detect
SPELL_AURA_MOD_INVISIBILITY = 18                   # Mod Invisibility
SPELL_AURA_MOD_INVISIBILITY_DETECTION = 19         # Mod Invisibility Detection
SPELL_AURA_MOD_POSSESS = 2                         # Mod Possess
SPELL_AURA_MOD_RESISTANCE = 22                     # Mod Resistance
SPELL_AURA_PERIODIC_TRIGGER_SPELL = 23             # Periodic Trigger
SPELL_AURA_PERIODIC_ENERGIZE = 24                  # Periodic Energize
SPELL_AURA_MOD_PACIFY = 25                         # Pacify
SPELL_AURA_MOD_ROOT = 26                           # Root
SPELL_AURA_MOD_SILENCE = 27                        # Silence
SPELL_AURA_REFLECT_SPELLS = 28                     # Reflect Spells %
SPELL_AURA_MOD_STAT = 29                           # Mod Stat
SPELL_AURA_PERIODIC_DAMAGE = 3                     # Periodic Damage
SPELL_AURA_MOD_SKILL = 30                          # Mod Skill
SPELL_AURA_MOD_INCREASE_SPEED = 31                 # Mod Speed
SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED = 32         # Mod Speed Mounted
SPELL_AURA_MOD_DECREASE_SPEED = 33                 # Mod Speed Slow
SPELL_AURA_MOD_INCREASE_HEALTH = 34                # Mod Increase Health
SPELL_AURA_MOD_INCREASE_ENERGY = 35                # Mod Increase Energy
SPELL_AURA_MOD_SHAPESHIFT = 36                     # Shapeshift
SPELL_AURA_EFFECT_IMMUNITY = 37                    # Immune Effect
SPELL_AURA_STATE_IMMUNITY = 38                     # Immune State
SPELL_AURA_SCHOOL_IMMUNITY = 39                    # Immune School
SPELL_AURA_DAMAGE_IMMUNITY = 40                    # Immune Damage
SPELL_AURA_DISPEL_IMMUNITY = 41                    # Immune Dispel Type
SPELL_AURA_PROC_TRIGGER_SPELL = 42                 # Proc Trigger Spell
SPELL_AURA_PROC_TRIGGER_DAMAGE = 43                # Proc Trigger Damage
SPELL_AURA_TRACK_CREATURES = 44                    # Track Creatures
SPELL_AURA_TRACK_RESOURCES = 45                    # Track Resources
SPELL_AURA_MOD_PARRY_SKILL = 46                    # Mod Parry Skill
SPELL_AURA_MOD_PARRY_PERCENT = 47                  # Mod Parry Percent
SPELL_AURA_MOD_DODGE_SKILL = 48                    # Mod Dodge Skill
SPELL_AURA_MOD_DODGE_PERCENT = 49                  # Mod Dodge Percent
SPELL_AURA_MOD_CONFUSE = 5                         # Mod Confuse
SPELL_AURA_MOD_BLOCK_SKILL = 50                    # Mod Block Skill
SPELL_AURA_MOD_BLOCK_PERCENT = 51                  # Mod Block Percent
SPELL_AURA_MOD_CRIT_PERCENT = 52                   # Mod Crit Percent
SPELL_AURA_PERIODIC_LEECH = 53                     # Periodic Leech
SPELL_AURA_MOD_HIT_CHANCE = 54                     # Mod Hit Chance
SPELL_AURA_MOD_SPELL_HIT_CHANCE = 55               # Mod Spell Hit Chance
SPELL_AURA_TRANSFORM = 56                          # Transform
SPELL_AURA_MOD_SPELL_CRIT_CHANCE = 57              # Mod Spell Crit Chance
SPELL_AURA_MOD_INCREASE_SWIM_SPEED = 58            # Mod Speed Swim
SPELL_AURA_MOD_DAMAGE_DONE_CREATURE = 59           # Mod Creature Dmg Done
SPELL_AURA_MOD_CHARM = 6                           # Mod Charm
SPELL_AURA_MOD_PACIFY_SILENCE = 60                 # Pacify & Silence
SPELL_AURA_MOD_SCALE = 61                          # Mod Scale
SPELL_AURA_PERIODIC_HEALTH_FUNNEL = 62             # Periodic Health Funnel
SPELL_AURA_PERIODIC_MANA_FUNNEL = 63               # Periodic Mana Funnel
SPELL_AURA_PERIODIC_MANA_LEECH = 64                # Periodic Mana Leech
SPELL_AURA_MOD_CASTING_SPEED = 65                  # Haste - Spells
SPELL_AURA_FEIGN_DEATH = 66                        # Feign Death
SPELL_AURA_MOD_DISARM = 67                         # Disarm
SPELL_AURA_MOD_STALKED = 68                        # Mod Stalked
SPELL_AURA_SCHOOL_ABSORB = 69                      # School Absorb
SPELL_AURA_MOD_FEAR = 7                            # Mod Fear
SPELL_AURA_EXTRA_ATTACKS = 70                      # Extra Attacks
SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL = 71       # Mod School Spell Crit Chance
SPELL_AURA_MOD_POWER_COST = 72                     # Mod Power Cost
SPELL_AURA_MOD_POWER_COST_SCHOOL = 73              # Mod School Power Cost
SPELL_AURA_REFLECT_SPELLS_SCHOOL = 74              # Reflect School Spells %
SPELL_AURA_MOD_LANGUAGE = 75                       # Mod Language
SPELL_AURA_FAR_SIGHT = 76                          # Far Sight
SPELL_AURA_MECHANIC_IMMUNITY = 77                  # Immune Mechanic
SPELL_AURA_MOUNTED = 78                            # Mounted
SPELL_AURA_MOD_DAMAGE_PERCENT_DONE = 79            # Mod Dmg %
SPELL_AURA_PERIODIC_HEAL = 8                       # Periodic Heal
SPELL_AURA_MOD_PERCENT_STAT = 80                   # Mod Stat %
SPELL_AURA_SPLIT_DAMAGE = 81                       # Split Damage
SPELL_AURA_WATER_BREATHING = 82                    # Water Breathing
SPELL_AURA_MOD_BASE_RESISTANCE = 83                # Mod Base Resistance
SPELL_AURA_MOD_REGEN = 84                          # Mod Health Regen
SPELL_AURA_MOD_POWER_REGEN = 85                    # Mod Power Regen
SPELL_AURA_CHANNEL_DEATH_ITEM = 86                 # Create Death Item
SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN = 87           # Mod Dmg % Taken
SPELL_AURA_MOD_PERCENT_REGEN = 88                  # Mod Health Regen Percent
SPELL_AURA_PERIODIC_DAMAGE_PERCENT = 89            # Periodic Damage Percent
SPELL_AURA_MOD_ATTACKSPEED = 9                     # Mod Attack Speed
SPELL_AURA_MOD_RESIST_CHANCE = 90                  # Mod Resist Chance
SPELL_AURA_MOD_DETECT_RANGE = 91                   # Mod Detect Range
SPELL_AURA_PREVENTS_FLEEING = 92                   # Prevent Fleeing
SPELL_AURA_MOD_UNATTACKABLE = 93                   # Mod Uninteractible
SPELL_AURA_INTERRUPT_REGEN = 94                    # Interrupt Regen
SPELL_AURA_GHOST = 95                              # Ghost
SPELL_AURA_SPELL_MAGNET = 96                       # Spell Magnet
SPELL_AURA_MANA_SHIELD = 97                        # Mana Shield
SPELL_AURA_MOD_SKILL_TALENT = 98                   # Mod Skill Talent
SPELL_AURA_MOD_ATTACK_POWER = 99                   # Mod Attack Power


#-----------------------------------------------------------------
# Cast fail reasons to return from CanCast if error happened
#-----------------------------------------------------------------
CAST_FAIL_ALREADY_FULL_HEALTH = 1
CAST_FAIL_ALREADY_FULL_RAGE = 2
CAST_FAIL_CREATURE_ALREADY_TAMING = 3
CAST_FAIL_ALREADY_HAVE_CHARM = 4
CAST_FAIL_ALREADY_HAVE_SUMMON = 5 
CAST_FAIL_ALREADY_OPEN = 6
CAST_FAIL_MORE_POWERFUL_SPELL_ACTIVE = 7
CAST_FAIL_NO_TARGET = 9
CAST_FAIL_INVALID_TARGET = 10
CAST_FAIL_CANT_BE_CHARMED = 11
CAST_FAIL_CANT_BE_DISENCHANTED = 12
CAST_FAIL_TARGET_IS_TAPPED = 13
CAST_FAIL_CANT_START_DUEL_INVISIBLE = 14
CAST_FAIL_CANT_START_DUEL_STEALTHED = 15
CAST_FAIL_TOO_CLOSE_TO_ENEMY = 16
CAST_FAIL_CANT_DO_THAT_YET = 17
CAST_FAIL_YOU_ARE_DEAD = 18
CAST_FAIL_OBJECT_ALREADY_BEING_USED = 19
CAST_FAIL_CANT_DO_WHILE_CONFUSED = 20
CAST_FAIL_MUST_HAVE_ITEM_EQUIPPED = 22
CAST_FAIL_MUST_HAVE_XXXX_EQUIPPED = 23
CAST_FAIL_INTERNAL_ERROR = 24
CAST_FAIL_FIZZLED = 25
CAST_FAIL_YOU_ARE_FLEEING = 26
CAST_FAIL_FOOD_TOO_LOWLEVEL_FOR_PET = 27
CAST_FAIL_TARGET_IS_TOO_HIGH = 28
CAST_FAIL_IMMUNE = 29
CAST_FAIL_INTERRUPTED = 30
CAST_FAIL_INTERRUPTED_COMBAT = 31
CAST_FAIL_ITEM_ALREADY_ENCHANTED = 32
CAST_FAIL_ITEM_IS_GONE = 33
CAST_FAIL_ENCHANT_NOT_EXISTING_ITEM = 35
CAST_FAIL_ITEM_NOT_READY = 36
CAST_FAIL_YOU_ARE_NOT_HIGH_ENOUGH = 37
CAST_FAIL_NOT_IN_LINE_OF_SIGHT = 38
CAST_FAIL_TARGET_TOO_LOW = 39
CAST_FAIL_SKILL_NOT_HIGH_ENOUGH = 40
CAST_FAIL_WEAPON_HAND_IS_EMPTY = 41
CAST_FAIL_CANT_DO_WHILE_MOVING = 42
CAST_FAIL_NEED_AMMO_IN_PAPERDOLL_SLOT = 43
CAST_FAIL_REQUIRES_SOMETHING = 44
CAST_FAIL_NEED_EXOTIC_AMMO = 45
CAST_FAIL_NO_PATH_AVAILABLE = 46
CAST_FAIL_NOT_BEHIND_TARGET = 47
CAST_FAIL_DIDNT_LAND_IN_FISHABLE_WATER = 48
CAST_FAIL_CANT_BE_CAST_HERE = 49
CAST_FAIL_NOT_IN_FRONT_OF_TARGET = 50
CAST_FAIL_NOT_IN_CONTROL_OF_ACTIONS = 51
CAST_FAIL_SPELL_NOT_LEARNED = 52
CAST_FAIL_CANT_USE_WHEN_MOUNTED = 53
CAST_FAIL_YOU_ARE_IN_FLIGHT = 54
CAST_FAIL_SPELL_NOT_READY_YET = 55
CAST_FAIL_CANT_DO_IN_SHAPESHIFT = 56
CAST_FAIL_HAVE_TO_BE_STANDING = 57
CAST_FAIL_CAN_USE_ONLY_ON_OWN_OBJECT = 58
CAST_FAIL_CANT_ENCHANT_TRADE_ITEM = 59
CAST_FAIL_HAVE_TO_BE_UNSHEATHED = 60       # yellow text
CAST_FAIL_CANT_CAST_AS_GHOST = 61
CAST_FAIL_NO_AMMO = 62
CAST_FAIL_NO_CHARGES_REMAIN = 63
CAST_FAIL_COMBO_POINTS_REQUIRED = 64
CAST_FAIL_NO_DUELING_HERE = 65
CAST_FAIL_NOT_ENOUGH_ENDURANCE = 66
CAST_FAIL_THERE_ARENT_ANY_FISH_HERE = 67
CAST_FAIL_CANT_USE_WHILE_SHAPESHIFTED = 68
CAST_FAIL_CANT_MOUNT_HERE = 69
CAST_FAIL_YOU_DO_NOT_HAVE_PET = 70
CAST_FAIL_NOT_ENOUGH_MANA = 71
CAST_FAIL_CANT_USE_WHILE_SWIMMING = 72
CAST_FAIL_CAN_ONLY_USE_AT_DAY = 73
CAST_FAIL_CAN_ONLY_USE_INDOORS = 74
CAST_FAIL_CAN_ONLY_USE_MOUNTED = 75
CAST_FAIL_CAN_ONLY_USE_AT_NIGHT = 76
CAST_FAIL_CAN_ONLY_USE_OUTDOORS = 77
CAST_FAIL_ONLY_SHAPESHIFTED = 78           # didn't display
CAST_FAIL_CAN_ONLY_USE_STEALTHED  = 79
CAST_FAIL_CAN_ONLY_USE_WHILE_SWIMMING = 80
CAST_FAIL_OUT_OF_RANGE = 81
CAST_FAIL_CANT_USE_WHILE_PACIFIED = 82
CAST_FAIL_YOU_ARE_POSSESSED = 83
CAST_FAIL_YOU_NEED_TO_BE_IN_XXX = 85
CAST_FAIL_REQUIRES_XXX = 86
CAST_FAIL_UNABLE_TO_MOVE = 87
CAST_FAIL_SILENCED = 88
CAST_FAIL_ANOTHER_ACTION_IS_IN_PROGRESS = 89
CAST_FAIL_ALREADY_LEARNED_THAT_SPELL = 90
CAST_FAIL_SPELL_NOT_AVAILABLE_TO_YOU = 91
CAST_FAIL_CANT_DO_WHILE_STUNNED = 92
CAST_FAIL_YOUR_TARGET_IS_DEAD = 93
CAST_FAIL_TARGET_IS_IN_COMBAT = 94
#CAST_FAIL_CANT_DO_THAT_YET = 95
CAST_FAIL_TARGET_IS_DUELING = 96
CAST_FAIL_TARGET_IS_ENEMY = 97
CAST_FAIL_TARGET_IS_TOO_ENRAGED_TO_CHARM = 98
CAST_FAIL_TARGET_IS_FRIENDLY = 99
CAST_FAIL_TARGET_CANT_BE_IN_COMBAT = 100
CAST_FAIL_CANT_TARGET_PLAYERS = 101
CAST_FAIL_TARGET_IS_ALIVE = 102
CAST_FAIL_TARGET_NOT_IN_YOUR_PARTY = 103
CAST_FAIL_CREATURE_MUST_BE_LOOTED_FIRST = 104
CAST_FAIL_NO_POCKETS_TO_PICK = 106
CAST_FAIL_TARGET_HAS_NO_WEAPONS_EQUIPPED = 107
CAST_FAIL_NOT_SKINNABLE = 108
CAST_FAIL_TOO_CLOSE = 110
CAST_FAIL_TOO_MANY_OF_THAT_ITEM_ALREADY = 111
CAST_FAIL_NOT_ENOUGH_TRAINING_POINTS = 113
CAST_FAIL_FAILED_ATTEMPT = 114
CAST_FAIL_TARGET_NEED_TO_BE_BEHIND = 115
CAST_FAIL_TARGET_NEED_TO_BE_INFRONT = 116
CAST_FAIL_PET_DOESNT_LIKE_THAT_FOOD = 117
CAST_FAIL_CANT_CAST_WHILE_FATIGUED = 118
CAST_FAIL_TARGET_MUST_BE_IN_THIS_INSTANCE = 119
CAST_FAIL_CANT_CAST_WHILE_TRADING = 120
CAST_FAIL_TARGET_IS_NOT_PARTY_OR_RAID = 121
CAST_FAIL_CANT_DISENCHANT_WHILE_LOOTING = 122


#--- END ---
