#
# Global constants used by scripts
#

RACE_UNDEFINED  = 0
RACE_HUMAN      = 1
RACE_ORC        = 2
RACE_DWARF      = 3
RACE_NIGHT_ELF  = 4
RACE_UNDEAD     = 5
RACE_TAUREN     = 6
RACE_GNOME      = 7
RACE_TROLL      = 8


CLASS_UNDEFINED = 0
CLASS_WARRIOR   = 1
CLASS_PALADIN   = 2
CLASS_HUNTER    = 3
CLASS_ROGUE     = 4
CLASS_PRIEST    = 5
CLASS_SHAMAN    = 7
CLASS_MAGE      = 8
CLASS_WARLOCK   = 9
CLASS_DRUID     = 11


GENDER_MALE     = 0
GENDER_FEMALE   = 1
GENDER_NONE     = 2


LANG_UNIVERSAL      = 0x00
LANG_ORCISH         = 0x01
LANG_DARNASSIAN     = 0x02
LANG_TAURAHE        = 0x03
LANG_DWARVISH       = 0x06
LANG_COMMON         = 0x07
LANG_DEMONIC        = 0x08
LANG_TITAN          = 0x09
LANG_THELASSIAN     = 0x0A
LANG_DRACONIC       = 0x0B
LANG_KALIMAG        = 0x0C
LANG_GNOMISH        = 0x0D
LANG_TROLL          = 0x0E
LANG_GUTTERSPEAK    = 0x21


EMOTE_ONESHOT_NONE                 = 0
EMOTE_ONESHOT_TALK                 = 1   # DNR
EMOTE_ONESHOT_BOW                  = 2
EMOTE_ONESHOT_WAVE                 = 3   # DNR
EMOTE_ONESHOT_CHEER                = 4   # DNR
EMOTE_ONESHOT_EXCLAMATION          = 5   # DNR
EMOTE_ONESHOT_QUESTION             = 6
EMOTE_ONESHOT_EAT                  = 7
EMOTE_STATE_DANCE                  = 10
EMOTE_ONESHOT_LAUGH                = 11
EMOTE_STATE_SLEEP                  = 12
EMOTE_STATE_SIT                    = 13
EMOTE_ONESHOT_RUDE                 = 14  # DNR
EMOTE_ONESHOT_ROAR                 = 15  # DNR
EMOTE_ONESHOT_KNEEL                = 16
EMOTE_ONESHOT_KISS                 = 17
EMOTE_ONESHOT_CRY                  = 18
EMOTE_ONESHOT_CHICKEN              = 19
EMOTE_ONESHOT_BEG                  = 20
EMOTE_ONESHOT_APPLAUD              = 21
EMOTE_ONESHOT_SHOUT                = 22  # DNR
EMOTE_ONESHOT_FLEX                 = 23
EMOTE_ONESHOT_SHY                  = 24  # DNR
EMOTE_ONESHOT_POINT                = 25  # DNR
EMOTE_STATE_STAND                  = 26
EMOTE_STATE_READYUNARMED           = 27
EMOTE_STATE_WORK                   = 28
EMOTE_STATE_POINT                  = 29  # DNR
EMOTE_STATE_NONE                   = 30
EMOTE_ONESHOT_WOUND                = 33
EMOTE_ONESHOT_WOUNDCRITICAL        = 34
EMOTE_ONESHOT_ATTACKUNARMED        = 35
EMOTE_ONESHOT_ATTACK1H             = 36
EMOTE_ONESHOT_ATTACK2HTIGHT        = 37
EMOTE_ONESHOT_ATTACK2HLOOSE        = 38
EMOTE_ONESHOT_PARRYUNARMED         = 39
EMOTE_ONESHOT_PARRYSHIELD          = 43
EMOTE_ONESHOT_READYUNARMED         = 44
EMOTE_ONESHOT_READY1H              = 45
EMOTE_ONESHOT_READYBOW             = 48
EMOTE_ONESHOT_SPELLPRECAST         = 50
EMOTE_ONESHOT_SPELLCAST            = 51
EMOTE_ONESHOT_BATTLEROAR           = 53
EMOTE_ONESHOT_SPECIALATTACK1H      = 54
EMOTE_ONESHOT_KICK                 = 60
EMOTE_ONESHOT_ATTACKTHROWN         = 61
EMOTE_STATE_STUN                   = 64
EMOTE_STATE_DEAD                   = 65
EMOTE_ONESHOT_SALUTE               = 66
EMOTE_STATE_KNEEL                  = 68
EMOTE_STATE_USESTANDING            = 69
EMOTE_ONESHOT_WAVE_NOSHEATHE       = 70
EMOTE_ONESHOT_CHEER_NOSHEATHE      = 71
EMOTE_ONESHOT_EAT_NOSHEATHE        = 92
EMOTE_STATE_STUN_NOSHEATHE         = 93
EMOTE_ONESHOT_DANCE                = 94
EMOTE_ONESHOT_SALUTE_NOSHEATH      = 113
EMOTE_STATE_USESTANDING_NOSHEATHE  = 133
EMOTE_ONESHOT_LAUGH_NOSHEATHE      = 153
EMOTE_STATE_WORK_NOSHEATHE         = 173
EMOTE_STATE_SPELLPRECAST           = 193
EMOTE_ONESHOT_READYRIFLE           = 213
EMOTE_STATE_READYRIFLE             = 214
EMOTE_STATE_WORK_NOSHEATHE_MINING  = 233
EMOTE_STATE_WORK_NOSHEATHE_CHOPWOOD= 234
EMOTE_zzOLDONESHOT_LIFTOFF         = 253
EMOTE_ONESHOT_LIFTOFF              = 254
EMOTE_ONESHOT_YES                  = 273 # DNR
EMOTE_ONESHOT_NO                   = 274 # DNR
EMOTE_ONESHOT_TRAIN                = 275 # DNR
EMOTE_ONESHOT_LAND                 = 293
EMOTE_STATE_READY1H                = 333
EMOTE_STATE_AT_EASE                = 313
EMOTE_STATE_SPELLKNEELSTART        = 353
EMOTE_STATE_SUBMERGED              = 373
EMOTE_ONESHOT_SUBMERGE             = 374


CREATURE_ELITE_NORMAL             = 0
CREATURE_ELITE_ELITE              = 1
CREATURE_ELITE_RAREELITE          = 2
CREATURE_ELITE_WORLDBOSS          = 3
CREATURE_ELITE_RARE               = 4


#--- END ---